### ISSUE TITLE
Game's audio is muted

### ISSUE THREAD

**Issue by vickyyproductionss** [yasirkula/UnitySpeechToText#1]
**Description of the bug**

I am using plugin to convert speech to text and later sending that text to my server to get response audio of the asked question.
When the response is returned and played the game becomes mute means i can't hear a single audio playing inside.
Looks like while starting the recording app mutes the audios.

**Reproduction steps**

1. Start recording and then play any sound.

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: 2022.3.4f1 metal
- Platform:  iOS
- Device: iPhone XS with iOS17.3 beta version
- How did you download the plugin: downloaded the plugin from git as .unitypackage

**Additional info**

**Comment by vickyyproductionss** [comment]
@yasirkula please have a look.

**Comment by yasirkula** [comment]
I didn't encounter this issue in my tests. It could be related to a project setting. For example, "Mute Other Audio Sources" is disabled in my project. Can you try disabling it? If that doesn't help, can you create a new project to see if the issue persists on a new project, as well?

**Comment by vickyyproductionss** [comment]
Possible you tested on unity version less than 2019.
I got the solution for anyone else facing this:
`#if UNITY_2019_3_OR_NEWER
            string targetGUID = project.GetUnityFrameworkTargetGuid();
#else
            string targetName = PBXProject.GetUnityTargetName();
            string targetGUID = project.TargetGuidByName(targetName);
#endif`

Updated BuildPostProcessor.cs Code with this.
Previously it was written to add speech.framework to unity-app to which i changed to:
`string targetGUID = project.GetUnityFrameworkTargetGuid();`.

BTW @yasirkula Thanks you've done amazing work.

**Comment by yasirkula** [comment]
I'm using 2021 LTS. This code should actually execute on versions above 2019.2:

https://github.com/yasirkula/UnitySpeechToText/blob/aedde04fd1daefe859d486061852bbb87fe4290c/Plugins/SpeechToText/Editor/STTPostProcessBuild.cs#L98-L100

So targetGUID is already assigned to GetUnityFrameworkTargetGuid. I'm confused but happy to hear that the issue's resolved. Can I see the latest version of the modified code?

**Comment by vickyyproductionss** [comment]
Extremely sorry i fixed that issue on someone else's repo.
Your repo has the correct code that repo was having build errors and yours was completing muting the applications audio and audio from youtube music and other apps as well.

**Comment by toptomsk** [comment]
@yasirkula i have face a problem with your package, whenever i use speechtotext, volume on my game decrease so much, maybe its cause AVAudioSession, i never face it before when using other package. Can you find out how to fix it?

**Comment by yasirkula** [comment]
I've pushed a fix for this issue. Please let me know if it doesn't work.
