### ISSUE TITLE
An issue where the overall volume of the game becomes smaller, after receiving speech to text, mic input from iOS

### ISSUE THREAD

**Issue by superbderrick** [yasirkula/UnitySpeechToText#7]
**Description of the bug**

hello. Thank you for making a great plugin. Thanks to you, I am making good games

On the iOS platform, the overall sound of the game becomes quiet after the init part. Is there a way to go back to the original game sound?

`
+ (int)initialize:(NSString *)language
{
	if( !CHECK_IOS_VERSION( @"10.0" ) || [self isBusy] == 1 )
		return 0;
	
	if( speechRecognizerLanguage == nil || ![speechRecognizerLanguage isEqualToString:language] )
	{
		speechRecognizerLanguage = language;
		
		[self cancel:NO];
		
		if( language == nil || [language length] == 0 )
			speechRecognizer = [[SFSpeechRecognizer alloc] init];
		else
			speechRecognizer = [[SFSpeechRecognizer alloc] initWithLocale:[NSLocale localeWithLocaleIdentifier:[language stringByReplacingOccurrencesOfString:@"-" withString:@"_"]]];
	}
	
	return ( speechRecognizer != nil ) ? 1 : 0;
}
`

**Reproduction steps**

If possible, providing reproduction steps would be very helpful while pinpointing the issue. You can also post screenshots if you think they would be helpful.

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: *e.g. 2021.3.36f1*
- Platform:  iOS
- Device:  Mostly iOS
- How did you download the plugin:GitHub

**Additional info**

Please check Logcat (Android) or Xcode console (iOS) for any meaningful error messages and include them here.

**Comment by yasirkula** [comment]
I've addressed this issue on [May 8 release](https://github.com/yasirkula/UnitySpeechToText/releases/tag/v1.1.0). Is your plugin up-to-date?

**Comment by superbderrick** [comment]
Hi @yasirkula  Thanks for replay, 
I will let u know after check with new version directly 
Cheers
Derrick

**Comment by superbderrick** [comment]
Hi @yasirkula  , We confirmed working well, 
Thanks for your help 
let me close the ticket 
Best,
Derrick
